apiVersion: apps/v1
kind: Deployment
metadata:
  name: searxng
  namespace: tools
  labels:
    app: searxng
spec:
  replicas: 1
  selector:
    matchLabels:
      app: searxng
  template:
    metadata:
      labels:
        app: searxng
    spec:
      enableServiceLinks: false
      containers:
        - name: searxng
          image: docker.io/searxng/searxng:latest
          ports:
            - containerPort: 8080
          env:
            - name: SEARXNG_SETTINGS_PATH
              value: /etc/searxng/settings.yml
            - name: SEARXNG_SECRET
              value: cc29a7f50612eb9d41d2697f85239bc71c0bd70fd72ed60196f110f4a485733d
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 10
          volumeMounts:
            - name: searxng-config
              mountPath: /etc/searxng/settings.yml
              subPath: settings.yml
      volumes:
        - name: searxng-config
          configMap:
            name: searxng-config
