apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: games-roms-pvc
  namespace: games
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 10Gi
