# PowerShell Script to Disable and Verify Windows 11 Telemetry Settings
# This script disables telemetry-related settings, services, scheduled tasks, and blocks telemetry domains.
# It verifies changes and reports if telemetry is fully disabled.
# Run as Administrator for full effect.
# Author: Grok (Generated by xAI)
# Date: October 15, 2025
# Disclaimer: Modifying system settings may affect functionality. Backup registry before running.

# Requires PowerShell 5.1 or later (default on Windows 11)

# Function to set registry value
function Set-RegistryValue {
    param (
        [string]$Path,
        [string]$Name,
        [object]$Value,
        [string]$Description
    )
    try {
        # Ensure the registry path exists
        if (-not (Test-Path $Path)) {
            New-Item -Path $Path -Force | Out-Null
        }
        Set-ItemProperty -Path $Path -Name $Name -Value $Value -Force -ErrorAction Stop
        Write-Output "[OK] Set $Description to $Value."
    } catch {
        Write-Output "[ERROR] Failed to set $Description. Error: $_"
        return $false
    }
    return $true
}

# Function to check registry value
function Check-RegistryValue {
    param (
        [string]$Path,
        [string]$Name,
        [object]$ExpectedValue,
        [string]$Description
    )
    try {
        $value = Get-ItemProperty -Path $Path -Name $Name -ErrorAction Stop | Select-Object -ExpandProperty $Name
        if ($value -eq $ExpectedValue) {
            Write-Output "[OK] $Description is $ExpectedValue (Telemetry off)."
            return $true
        } else {
            Write-Output "[WARNING] $Description is $value (Expected: $ExpectedValue). Telemetry may be active."
            return $false
        }
    } catch {
        Write-Output "[ERROR] $Description registry key not found or access denied."
        return $false
    }
}

# Function to disable and stop a service
function Disable-Service {
    param (
        [string]$ServiceName,
        [string]$Description
    )
    try {
        $service = Get-Service -Name $ServiceName -ErrorAction Stop
        if ($service.Status -ne "Stopped") {
            Stop-Service -Name $ServiceName -Force -ErrorAction Stop
            Write-Output "[OK] Stopped $Description service."
        }
        Set-Service -Name $ServiceName -StartupType Disabled -ErrorAction Stop
        Write-Output "[OK] Disabled $Description service."
        return $true
    } catch {
        Write-Output "[ERROR] Failed to manage $Description service. Error: $_"
        return $false
    }
}

# Function to check service status
function Check-ServiceStatus {
    param (
        [string]$ServiceName,
        [string]$Description
    )
    try {
        $service = Get-Service -Name $ServiceName -ErrorAction Stop
        $wmiService = Get-WmiObject -Class Win32_Service -Filter "Name='$ServiceName'"
        if ($service.Status -eq "Stopped" -and $wmiService.StartMode -eq "Disabled") {
            Write-Output "[OK] $Description service is Stopped and Disabled (Telemetry off)."
            return $true
        } else {
            Write-Output "[WARNING] $Description service is $($service.Status) and startup type is $($wmiService.StartMode). Telemetry may be active."
            return $false
        }
    } catch {
        Write-Output "[ERROR] $Description service not found or access denied."
        return $false
    }
}

# Function to disable scheduled task
function Disable-ScheduledTaskCustom {
    param (
        [string]$TaskPath,
        [string]$TaskName,
        [string]$Description
    )
    try {
        Disable-ScheduledTask -TaskPath $TaskPath -TaskName $TaskName -ErrorAction Stop
        Write-Output "[OK] Disabled $Description task."
        return $true
    } catch {
        Write-Output "[ERROR] Failed to disable $Description task. Error: $_"
        return $false
    }
}

# Function to check scheduled task status
function Check-ScheduledTask {
    param (
        [string]$TaskPath,
        [string]$TaskName,
        [string]$Description
    )
    try {
        $task = Get-ScheduledTask -TaskPath $TaskPath -TaskName $TaskName -ErrorAction Stop
        if ($task.State -eq "Disabled") {
            Write-Output "[OK] $Description task is Disabled (Telemetry off)."
            return $true
        } else {
            Write-Output "[WARNING] $Description task is $($task.State). Telemetry may be active."
            return $false
        }
    } catch {
        Write-Output "[ERROR] $Description task not found or access denied."
        return $false
    }
}

# Function to block telemetry domains in hosts file
function Block-TelemetryDomains {
    param (
        [string[]]$Domains,
        [string]$Description
    )
    $hostsPath = "$env:windir\System32\drivers\etc\hosts"
    try {
        $hostsContent = Get-Content -Path $hostsPath -ErrorAction Stop
        $newLines = @()
        foreach ($domain in $Domains) {
            if ($hostsContent -notmatch "127.0.0.1\s+$domain" -and $hostsContent -notmatch "0.0.0.0\s+$domain") {
                $newLines += "0.0.0.0 $domain"
                Write-Output "[OK] Added $domain to hosts file."
            } else {
                Write-Output "[OK] $domain already blocked in hosts file."
            }
        }
        if ($newLines) {
            Add-Content -Path $hostsPath -Value $newLines -ErrorAction Stop
            Write-Output "[OK] Updated hosts file with telemetry domains."
            # Flush DNS cache
            ipconfig /flushdns | Out-Null
            Write-Output "[OK] Flushed DNS cache."
        }
        return $true
    } catch {
        Write-Output "[ERROR] Failed to update hosts file for $Description. Error: $_"
        return $false
    }
}

# Function to check telemetry domains in hosts file
function Check-TelemetryDomains {
    param (
        [string[]]$Domains,
        [string]$Description
    )
    $hostsPath = "$env:windir\System32\drivers\etc\hosts"
    try {
        $hostsContent = Get-Content -Path $hostsPath -ErrorAction Stop
        $allBlocked = $true
        foreach ($domain in $Domains) {
            if ($hostsContent -match "127.0.0.1\s+$domain" -or $hostsContent -match "0.0.0.0\s+$domain") {
                Write-Output "[OK] $domain is blocked in hosts file."
            } else {
                Write-Output "[WARNING] $domain is NOT blocked in hosts file."
                $allBlocked = $false
            }
        }
        return $allBlocked
    } catch {
        Write-Output "[ERROR] Failed to read hosts file for $Description. Error: $_"
        return $false
    }
}

# Main script execution
Write-Output "Starting Windows 11 Telemetry Disabler and Verifier..."
Write-Output "Current user: $(whoami)"
Write-Output "Note: This script requires Administrator privileges to modify system settings."

$isAdmin = ([Security.Principal.WindowsPrincipal] [Security.Principal.WindowsIdentity]::GetCurrent()).IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)
if (-not $isAdmin) {
    Write-Output "[ERROR] This script must be run as Administrator. Please re-run with elevated privileges."
    exit 1
}

$success = $true

# Section 1: Disable Telemetry via Registry
Write-Output "`n--- Disabling Registry Settings ---"
$success = $success -and (Set-RegistryValue -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection" -Name "AllowTelemetry" -Value 0 -Description "AllowTelemetry policy")
$success = $success -and (Set-RegistryValue -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection" -Name "AllowTelemetry" -Value 0 -Description "AllowTelemetry (CurrentVersion)")
$success = $success -and (Set-RegistryValue -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection" -Name "LimitEnhancedDiagnosticDataWindowsAnalytics" -Value 1 -Description "LimitEnhancedDiagnosticData")
$success = $success -and (Set-RegistryValue -Path "HKLM:\SYSTEM\ControlSet001\Control\WMI\Autologger\AutoLogger-Diagtrack-Listener" -Name "Start" -Value 0 -Description "DiagTrack AutoLogger")
$success = $success -and (Set-RegistryValue -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Diagnostics\DiagTrack" -Name "ShowedToastAtLevel" -Value 1 -Description "DiagTrack Toast Level")
$success = $success -and (Set-RegistryValue -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Privacy" -Name "TailoredExperiencesWithDiagnosticDataEnabled" -Value 0 -Description "Tailored experiences")
$success = $success -and (Set-RegistryValue -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Privacy" -Name "HasAdvertisingIdEnabled" -Value 0 -Description "Advertising ID")
$success = $success -and (Set-RegistryValue -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SubscribedContent-338387Enabled" -Value 0 -Description "Suggested content")

# Section 2: Disable Telemetry Services
Write-Output "`n--- Disabling Services ---"
$success = $success -and (Disable-Service -ServiceName "DiagTrack" -Description "Connected User Experiences and Telemetry")
$success = $success -and (Disable-Service -ServiceName "dmwappushservice" -Description "WAP Push Message Routing Service")

# Section 3: Disable Telemetry Scheduled Tasks
Write-Output "`n--- Disabling Scheduled Tasks ---"
$success = $success -and (Disable-ScheduledTaskCustom -TaskPath "\Microsoft\Windows\Application Experience\" -TaskName "Microsoft Compatibility Appraiser" -Description "Microsoft Compatibility Appraiser")
$success = $success -and (Disable-ScheduledTaskCustom -TaskPath "\Microsoft\Windows\Customer Experience Improvement Program\" -TaskName "Consolidator" -Description "CEIP Consolidator")
$success = $success -and (Disable-ScheduledTaskCustom -TaskPath "\Microsoft\Windows\Customer Experience Improvement Program\" -TaskName "UsbCeip" -Description "USB CEIP")
$success = $success -and (Disable-ScheduledTaskCustom -TaskPath "\Microsoft\Windows\Autochk\" -TaskName "Proxy" -Description "Autochk Proxy")
$success = $success -and (Disable-ScheduledTaskCustom -TaskPath "\Microsoft\Windows\DiskDiagnostic\" -TaskName "Microsoft-Windows-DiskDiagnosticDataCollector" -Description "Disk Diagnostic Data Collector")

# Section 4: Block Telemetry Domains in Hosts File
Write-Output "`n--- Blocking Telemetry Domains ---"
$telemetryDomains = @("vortex.data.microsoft.com", "settings-win.data.microsoft.com", "telecommand.telemetry.microsoft.com")
$success = $success -and (Block-TelemetryDomains -Domains $telemetryDomains -Description "Telemetry domains")

# Section 5: Verify All Settings
Write-Output "`n--- Verifying Telemetry Settings ---"
$allOff = $true

# Verify Registry
Write-Output "`n--- Registry Verification ---"
$allOff = $allOff -and (Check-RegistryValue -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection" -Name "AllowTelemetry" -ExpectedValue 0 -Description "AllowTelemetry policy")
$allOff = $allOff -and (Check-RegistryValue -Path "HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\DataCollection" -Name "AllowTelemetry" -ExpectedValue 0 -Description "AllowTelemetry (CurrentVersion)")
$allOff = $allOff -and (Check-RegistryValue -Path "HKLM:\SOFTWARE\Policies\Microsoft\Windows\DataCollection" -Name "LimitEnhancedDiagnosticDataWindowsAnalytics" -ExpectedValue 1 -Description "LimitEnhancedDiagnosticData")
$allOff = $allOff -and (Check-RegistryValue -Path "HKLM:\SYSTEM\ControlSet001\Control\WMI\Autologger\AutoLogger-Diagtrack-Listener" -Name "Start" -ExpectedValue 0 -Description "DiagTrack AutoLogger")
$allOff = $allOff -and (Check-RegistryValue -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Diagnostics\DiagTrack" -Name "ShowedToastAtLevel" -ExpectedValue 1 -Description "DiagTrack Toast Level")
$allOff = $allOff -and (Check-RegistryValue -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Privacy" -Name "TailoredExperiencesWithDiagnosticDataEnabled" -ExpectedValue 0 -Description "Tailored experiences")
$allOff = $allOff -and (Check-RegistryValue -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\Privacy" -Name "HasAdvertisingIdEnabled" -ExpectedValue 0 -Description "Advertising ID")
$allOff = $allOff -and (Check-RegistryValue -Path "HKCU:\Software\Microsoft\Windows\CurrentVersion\ContentDeliveryManager" -Name "SubscribedContent-338387Enabled" -ExpectedValue 0 -Description "Suggested content")

# Verify Services
Write-Output "`n--- Service Verification ---"
$allOff = $allOff -and (Check-ServiceStatus -ServiceName "DiagTrack" -Description "Connected User Experiences and Telemetry")
$allOff = $allOff -and (Check-ServiceStatus -ServiceName "dmwappushservice" -Description "WAP Push Message Routing Service")

# Verify Scheduled Tasks
Write-Output "`n--- Scheduled Task Verification ---"
$allOff = $allOff -and (Check-ScheduledTask -TaskPath "\Microsoft\Windows\Application Experience\" -TaskName "Microsoft Compatibility Appraiser" -Description "Microsoft Compatibility Appraiser")
$allOff = $allOff -and (Check-ScheduledTask -TaskPath "\Microsoft\Windows\Customer Experience Improvement Program\" -TaskName "Consolidator" -Description "CEIP Consolidator")
$allOff = $allOff -and (Check-ScheduledTask -TaskPath "\Microsoft\Windows\Customer Experience Improvement Program\" -TaskName "UsbCeip" -Description "USB CEIP")
$allOff = $allOff -and (Check-ScheduledTask -TaskPath "\Microsoft\Windows\Autochk\" -TaskName "Proxy" -Description "Autochk Proxy")
$allOff = $allOff -and (Check-ScheduledTask -TaskPath "\Microsoft\Windows\DiskDiagnostic\" -TaskName "Microsoft-Windows-DiskDiagnosticDataCollector" -Description "Disk Diagnostic Data Collector")

# Verify Telemetry Domains
Write-Output "`n--- Telemetry Domains Verification ---"
$allOff = $allOff -and (Check-TelemetryDomains -Domains $telemetryDomains -Description "Telemetry domains")

# Final Verdict
Write-Output "`n--- Final Verdict ---"
if ($allOff -and $success) {
    Write-Output "SUCCESS: All telemetry settings are disabled. Telemetry is fully OFF in Windows 11."
} else {
    Write-Output "WARNING: Some telemetry settings could not be disabled or are still active. Review errors/warnings above."
}

Write-Output "`n--- Notes ---"
Write-Output "1. Re-run this script after Windows updates, as they may re-enable telemetry."
Write-Output "2. To revert changes, manually re-enable services/tasks or restore registry backups."
Write-Output "3. For additional protection, consider firewall rules to block telemetry IPs."
Write-Output "Script complete."
